site_name: Chalmers Qubit Simulator
theme:
  name: material
  language: en 
  palette:

    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

  features:
    - content.code.copy
    - search.suggest
    - search.highlight
    - content.tabs.link

plugins:
  - search
  - bibtex:
      bib_file: "docs/bibliography/references.bib"

markdown_extensions:
  - footnotes
  # Enable MathJax
  - pymdownx.arithmatex:
      generic: true

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      linenums: true # show line numbers
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

copyright: Copyright &copy; 2024

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js